### ISSUE TITLE
ENTRYPOINT should have only html5validator

### ISSUE THREAD

**Issue by fauust** [Cyb3r-Jak3/html5validator-docker#7] opened 2020-10-02 11:03 UTC
Hi!
If I am not misunderstanding how `ENTRYPOINT` works, your `Dockerfiles` should contain
```dockerfiles
  ENTRYPOINT [ "html5validator" ]
```
instead of
```dockerfiles
  ENTRYPOINT [ "html5validator", "--help" ]
```

Because calling the docker container, show `html5validator` help, no mater which argument is passed. Worse, this is always true in the context of CI so, the validation is always OK.

I am calling it from gitlab-ci with:
```yaml
check_html:
  stage: check_html
  image: cyb3rjak3/html5validator:latest-alpine
  script:
    - html5validator --root public/ --format text
```

**Comment by fauust** [comment] 2020-10-02 11:22
Side note: my CI was working 2 weeks ago, so I am not sure if there was a change in GitlabCI or if you changed something to your containers.

Anyway, I believe that it would be good to be able to use your container directly from the CLI with something like:
```console
docker run --rm -i -v $(pwd):/mnt cyb3rjak3/html5validator:latest-alpine --root public/
```

**Comment by kerbe** [comment] 2020-10-07 11:06
I think I am running in same issue as fauust. I had Gitlab jobs set up, and had made changes 4 months ago. Now that I made some tweaks, I noticed that actual validations wasn't done. And worse, it didn't fail either, it just had printed help to output. Some fixing is needed @Cyb3r-Jak3 :)

**Comment by Cyb3r-Jak3** [comment] 2020-10-07 13:28
Yup you are right it should by just html5validator in the entry point. I apologise, there are no tests currently for straight docker container. 

Should be fixed by tomorrow.

@kerbe if you notice that your CI still fails after this is patched then please let me know.

**Comment by Cyb3r-Jak3** [comment] 2020-10-08 00:20
@fauust @kerbe 

When you get a chance please rerun your jobs. I have removed the extra entrypoint. I have also added tests to prevent something like from happening again.

**Comment by kerbe** [comment] 2020-10-08 01:30
@Cyb3r-Jak3 Mhh, I went and hit re-run on my Gitlab job, and I also tried making new commits to get new job running. Doesn't seem to be working as it used to, as Gitlab doesn't actually run script now.

I have followed instructions here:
https://github.com/svenkreiss/html5validator#integration-with-gitlab-ci

This is my gitlab-ci.yml regarding that part:
```
html_test:
  stage: test
  image: cyb3rjak3/html5validator:latest
  script:
    - html5validator --root ./ --also-check-css --blacklist vendor --log INFO --format json
```

Is intended behavior and way this should be called changed on purpose, or is there still some problem? Either way is fine for me, I can change my .gitlab-ci.yml, but then that help should also be changed. :)

This is job output with that configuration as of now:
```
Running with gitlab-runner 13.4.1 (e95f89a0)
  on docker-auto-scale fa6cab46
Preparing the "docker+machine" executor
Using Docker executor with image cyb3rjak3/html5validator:latest ...
Pulling docker image cyb3rjak3/html5validator:latest ...
Using docker image sha256:8faed751a0d24508a220af17db2caa1523aeed3c8a8b5256d120beefdf31c639 for cyb3rjak3/html5validator:latest with digest cyb3rjak3/html5validator@sha256:ece96dd061367b6ffda5adc90036699f9daeb5e217814701a6d34b899dc75a23 ...
Preparing environment
Running on runner-fa6cab46-project-14118051-concurrent-0 via runner-fa6cab46-srm-1602119703-ef62363d...
Getting source from Git repository
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/lunanova/website/lunanova.fi/.git/
Created fresh repository.
Checking out 82b77856 as 6-countdown-for-big-news...
Skipping Git submodules setup
Executing "step_script" stage of the job script
Cleaning up file based variables
Job succeeded
```

**Comment by Cyb3r-Jak3** [comment] 2020-10-08 02:12
@kerbe You should be all set now

**Comment by kerbe** [comment] 2020-10-08 02:29
Thank you @Cyb3r-Jak3, I just retried latest job and now it behaves as it used to be. So seems to be working!

**Comment by fauust** [comment] 2020-10-08 15:35
Hi @Cyb3r-Jak3! Thank you for the change.
It seems my CI is green again (well green **with** html5 validation ;-))

On the documentation aspect, I am missing in the README a line on how to use the container to validate a local html file (without passing by a CI system).

Something like in that project README:
https://github.com/hadolint/hadolint/tree/master/docker#usage ?

Anyway, good work, those are very useful containers!

**Comment by Cyb3r-Jak3** [comment] 2020-10-08 23:44
@fauust I have updated the README.md with better examples of use. Let me know what you think.

**Comment by fauust** [comment] 2020-10-09 07:38
Thanks @Cyb3r-Jak3, see https://github.com/Cyb3r-Jak3/html5validator-docker/pull/11

**Closed** 2020-10-09 22:05 UTC
Labels: bug
